Merge Dev to Main
CodeNextPaco/Weatherly pull request #9
Opened 2022-07-20 08:54 UTC by derekc00

2022-07-23 01:03 UTC, CodeNextPaco requested changes

2022-07-23 01:03 UTC, CodeNextPaco commented on Weatherly/Model/APIManager.swift
> +  static private let apiKey = "1495b6e70be9d92ba6cafc1c60e83bd6"
Let's remove this. I got a complaint about it.

2022-07-23 01:03 UTC, CodeNextPaco commented on Weatherly/Model/APIManager.swift
> +  static private let apiKey = "1495b6e70be9d92ba6cafc1c60e83bd6"
Or hide the API key

2022-07-24 02:28 UTC, derekc00 commented
I removed the key and added a line inside the readme to provide instruction on this

2022-07-25 18:14 UTC, CodeNextPaco approved these changes
Looks good now! Thanks

2022-07-25 18:14 UTC, merged